apiVersion: v1
kind: Service
metadata:
  name: gobotsv
  labels:
    name: app
    app: gobot
spec:
  ports:
    - name: gobot
      port: 3000
      targetPort: 3000
  selector:
    name: app
    app: gobot
    color: blue
  type: LoadBalancer
