apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gobotblue
  labels:
    name: app
    app: gobot
    color: blue
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 4
  template:
    metadata:
      name: gobotblue
      labels:
        name: app
        app: gobot
        color: blue
    spec:
      containers:
      - image: tbuchi888/gobotblue:v1
        name: gobot
        ports:
          - containerPort: 3000
        env:
          - name: GOBOTTOKEN
            value: Your_slashcommand_token
