apiVersion: v1
kind: Service
metadata:
  name: mattermostsv
  labels:
    name: app
    app: mattermost
spec:
  ports:
    - name: mattermost
      port: 8065
      targetPort: 8065
  selector:
    name: app
    app: mattermost
    color: blue
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mattermostdep
  labels:
    name: app
    app: mattermost
    color: blue
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      name: mattermosttmp
      labels:
        name: app
        app: mattermost
        color: blue
    spec:
      containers:
      - image: mattermost/mattermost-preview:latest 
        name: blue
        ports:
          - containerPort: 8065
